project_name: sql
release:
  github:
    owner: marianogappa
    name: sql
brew:
  install: bin.install "sql"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  env:
    - CGO_ENABLED=0
