version: "3.9"
services:
  test:
    build: .
    volumes:
      - "$PWD:/go/src/sql"
    working_dir: /go/src/sql
    depends_on:
      - mysql
      - postgres
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql_test_schemas.sql:/docker-entrypoint-initdb.d/mysql_test_schemas.sql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  postgres:
    image: postgres:9-alpine
    volumes:
      - ./postgres_test_schemas.sql:/docker-entrypoint-initdb.d/postgres_test_schemas.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 
      POSTGRES_HOST_AUTH_METHOD: trust
