version: '3'
services:
  test:
    build: .
    volumes:
      - "$PWD:/go/src/sql"
    working_dir: /go/src/sql
    depends_on:
      - test-mysql
  test-mysql:
    image: mysql:5
    volumes:
      - ./test_schemas.sql:/docker-entrypoint-initdb.d/test_schemas.sql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
